// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'clearLookupButton': string;
  'helpText': string;
  'mangaAuthor': string;
  'mangaCover': string;
  'mangaInfo': string;
  'mangaOverview': string;
  'mangaResult': string;
  'mangaStatus': string;
  'mangaTitle': string;
  'mangaYear': string;
  'message': string;
  'noResults': string;
  'searchContainer': string;
  'searchIconContainer': string;
  'searchInput': string;
  'searchResults': string;
}
export const cssExports: CssExports;
export default cssExports;
