// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addButton': string;
  'author': string;
  'container': string;
  'info': string;
  'modalFooter': string;
  'overview': string;
  'poster': string;
  'posterImage': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
